include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    require_trailing_commas: true
    prefer_const_constructors: false
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: false
    unnecessary_string_interpolations: false
